name: Github Action Demo

on:
  push:

jobs:
  Action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        uses: actions/Checkout@v4
      - name: Print index.html file
        run: cat index.html
          
          

 
